routes/web.php
<?php


Route::get('/', 'HomeController@index')->name('index');
Route::get('/token', 'UsersController@generateToken');
Route::get('/country','CountryController@index')->name('country.dashboard');


Auth::routes(['verify' => true]);

Route::get('create-password', 'Auth\CreatePasswordController@index')->name('create-password-index');
Route::post('create-password', 'Auth\CreatePasswordController@store')->name('create-password');

Route::group(['middleware'=>'auth'], function() {

Route::group(['middleware'=>'administrator','prefix'=>'users'],function () {
    Route::get('/', 'UsersController@index')->name('users.index');
    Route::post('/', 'UsersController@store')->name('users.store');
    Route::post('/update', 'UsersController@update')->name('users.update');
    Route::post('/updateFew', 'UsersController@updateFew')->name('users.updateFew');
    Route::delete('/{user_id}', 'UsersController@destroy')->name('users.destroy');
    Route::post('/{user_id}', 'UsersController@restore')->name('users.restore');

});

Route::post('/missed-card-payment', 'PaymentsController@missedCardPayment')->name('missed-card-payment');
Route::prefix('cooperatives')->group(function () {
    Route::get('/', 'cooperativesController@index')->name('cooperatives.index');    
    Route::post('/', 'cooperativesController@store')->name('cooperatives.store');
    Route::post('/update', 'cooperativesController@update')->name('cooperatives.update');
    Route::post('/destroy', 'cooperativesController@destroy')->name('cooperatives.destroy'); 
});
Route::prefix('bonus')->group(function () {
Route::post('/store', 'BonusController@store')->name('bonus.store');
});
Route::post('sendSms','SmsController@sms')->name('sms');
Route::post('sms_destroy','SmsController@sms_destroy')->name('sms_destroy');
Route::resource('sms','SmsController');


Route::get('/deleted_users', 'UsersController@deleted_users')->name('users.deleted');


Route::prefix('ajax')->group(function() {
    Route::get('users', 'UsersController@getUsers');
    Route::get('deleted_users', 'UsersController@getDeletedUsers');
    Route::get('districts', 'DataController@getDistricts');
    Route::get('sectors', 'DataController@getSectors');
    Route::get('cells', 'DataController@getCells');
    Route::get('villages', 'DataController@getVillages');
});
Route::get('/edit/{id}', 'UsersController@edit')->name('users_edit');


//Route::get('/login_page', function () { return view('pages.login');})->name('login_page');
//Route::get('/country','CountryController@index')->name('country');
Route::get('/district/{id}', 'DistrictController@index')->name('district');
Route::get('/province/{id}', 'ProvinceController@index')->name('province');
Route::get('/sector/{id}', 'SectorController@index')->name('sector');
Route::get('/cooperative/{id}', 'CooperativeController@index')->name('cooperative');
Route::get('/cooperatives_list/{id}', 'CooperativeController@cooperatives')->name('cooperatives');
Route::post('/update_cooperative', 'cooperativesController@update')->name('update_cooperative');
Route::post('/register_cooperative', 'cooperativesController@store')->name('register_cooperative');
//Route::get('/home', 'HomeController@index')->name('home');
Route::post('/update_user', 'UsersController@update')->name('update_user');
Route::post('/register_user', 'UsersController@create')->name('register_user');
Route::get('/password_generate/{id}', 'UsersController@password_generate')->name('password_generate');
Route::post('/password_update', 'UsersController@password_update')->name('password_update');
//Route::post('dynamic_dependent/fetch', 'UsersController@fetch')->name('dynamicdependent.fetch');

//Route::get('/test', 'PaymentsController@test')->name('cooperatives');

Route::resource('motorcyclist', 'MotorcyclistController');
Route::post('/motorcyclist_update', 'MotorcyclistController@update')->name('motorcyclist_update');
Route::post('/motorcyclist_delete', 'MotorcyclistController@destroy')->name('motorcyclist_delete');

Route::get('/card/{type}/{id}', 'MotorcyclistController@card')->name('card');

// Route::get('/cooperative_cards/{id}', 'MotorcyclistController@cooperative_cards')->name('cooperative_cards');
Route::post('/card_id', 'MotorcyclistController@card_id')->name('card_id');
Route::get('/reloadFailed', 'BprResponseController@reloadFailed')->name('reloadFailed');
});
Route::view('/search', 'pages.search')->name('search');
Route::any("/motari", "API\MotocyclistController@info")->name('info');

// Route::prefix('v1')->group(function () {    
//     Route::post('validate', 'API\MotocyclistController@motari_equity');
// });

app/User.php
<?php

namespace App;

use App\Notifications\EmailVerification;
use App\Traits\UuidModel;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * App\User
 *
 * @property string $id
 * @property string $name
 * @property string|null $email
 * @property string $telephone
 * @property string|null $national_id
 * @property string|null $province
 * @property string|null $district
 * @property string|null $sector
 * @property string|null $otp
 * @property bool $otp_status
 * @property int $status
 * @property \Illuminate\Support\Carbon|null $email_verified_at
 * @property string $password
 * @property string|null $remember_token
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @property-read int|null $notifications_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\PaymentTransaction[] $paymentTransactions
 * @property-read int|null $payment_transactions_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\Spatie\Permission\Models\Permission[] $permissions
 * @property-read int|null $permissions_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Role[] $roles
 * @property-read int|null $roles_count
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User newQuery()
 * @method static \Illuminate\Database\Query\Builder|\App\User onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User permission($permissions)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User query()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User role($roles, $guard = null)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User uuid($uuid, $first = true)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereDistrict($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereEmailVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereNationalId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereOtp($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereOtpStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereProvince($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereSector($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereTelephone($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\User withTrashed()
 * @method static \Illuminate\Database\Query\Builder|\App\User withoutTrashed()
 * @mixin \Eloquent
 */
class User extends Authenticatable implements MustVerifyEmail
{
    use UuidModel, Notifiable, SoftDeletes, HasRoles,HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id','name', 'email', 'telephone', 'national_id', 'province', 'district', 'sector', 'otp', 'otp_status', 'status', 'email_verified_at', 'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'string', 'email_verified_at' => 'datetime', 'otp_status' => 'boolean'
    ];

    public $incrementing = false;

    public function paymentTransactions() {
        return $this->hasMany(PaymentTransaction::class);
    }

    /**
     * Send the email verification notification.
     *
     * @return void
     */
    public function sendEmailVerificationNotification() {
        $this->notify(new EmailVerification());

    }

    public function getDeploymentAttribute() {

        if ($this->relationLoaded('roles') && $this->roles->isNotEmpty()) {
            if ($this->roles->first()->name == 'admin')
                return '-';

            if ($this->roles->first()->name == 'regional_coordinator')
                return $this->province;

            if ($this->roles->first()->name == 'district_leader')
                return $this->province . ', ' . $this->district;
        }

        return $this->province . ', ' . $this->district . ', ' . $this->sector;
    }

    public function house()
    {
      return $this->hasMany(House::class);
    }   
    public function rwanda_adus()
    {
      return $this->belongsTo(RwandaADU::class,'rwandaADU_id','id');
    }  
}

resources/views/pages/users/index.blade.php
@extends('layouts.master')

@section('title', 'Users')

@push('styles')
    <link href="{{ asset('assets/vendors/general/morris.js/morris.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('assets/vendors/general/sweetalert2/dist/sweetalert2.css')}}" rel="stylesheet"
          type="text/css"/>
    <style type="text/css">

        .users-filter {
            background: #e1e3ec;
            margin-right: 7px;
        }

        .select2-container {
            margin-right: 10px;
        }


        .btn.btn-clean i {
            color: #2dc7bf;
        }

    </style>

@endpush

@section('content')
    <!-- begin:: Subheader -->
    <div class="kt-subheader   kt-grid__item" id="kt_subheader">
    </div>
    <!-- end:: Subheader -->
    <!-- begin:: Content -->
    <div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
        <!--Begin::Dashboard 3-->
        <div class="row">
            <div class="col-md-12">
{{--             @include('include.messages')
 --}}            <!--Begin::Section-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="kt-portlet kt-portlet--height-fluid kt-portlet--mobile ">
                            <div
                                class="kt-portlet__head kt-portlet__head--lg kt-portlet__head--noborder kt-portlet__head--break-sm">
                                <div class="kt-portlet__head-label">
                                    <button type="button" class="btn btn-primary" data-toggle="modal"
                                            data-target="#add_user_modal">
                                        <i class="flaticon2-plus-1"></i>
                                        Add New User
                                    </button>
                <span class="dropdown"> 
                    <a href="#" class="btn btn-sm btn-clean btn-icon btn-icon-md" data-toggle="dropdown" aria-expanded="true"> 
                        <i class="la la-ellipsis-h"></i> 
                    </a> 
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="{{route('users.index')}}">
                            <i class="la la-lock"></i> Active Users
                        </a>                         
                         <a class="dropdown-item" href="{{route('users.deleted')}}">
                         <i class="la la-ellipsis-h"></i>Deleted Users 
                         </a> 
                    </div> 
                </span> 

                                    <!--begin::Modal-->
@include('include.add_user_modal')                                    
@include('include.edit_user_modal')                                    
                                    <!-- end modal -->
                                </div>
{{--                                 @include('pages.users.partials.filter')
 --}}                            </div>
                            <div class="kt-portlet__body">
                                <!--begin: Datatable -->
                                <!-- <div class="kt-datatable" id="kt_datatable_latest_orders"></div> -->
                                <!--begin: Datatable -->
                                <table class="table table-striped- table-bordered table-hover table-checkable"
                                       id="kt_table_1_2">
                                    <thead>
                                        <tr>
                                            <th class="text-center">#</th>
                                            <th>Name</th>
                                            <th>Role</th>
                                            <th>Phone</th>
                                            <th>E-mail</th>
{{--                                             <th>Deployment Location</th>
 --}}                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    {{--<tbody>
                                        @foreach($users as $key => $user)
                                            <tr>
                                                <td class="text-center">{{ ($key + 1) }}</td>
                                                <td>{{ $user->name }}</td>
                                                <td>{{ $user->roles()->pluck('display_name')->implode(', ')}}</td>
                                                <td>{{ $user->telephone}}</td>
                                                <td>{{ $user->email}}</td>
                                                <td>{{ $user->deployment }}</td>
                                                <td>
                                                    --}}{{--<button type="button" class="btn btn-primary"
                                                            data-full_name="{{$name}}" data-telephone="{{$telephone}}"
                                                            data-email="{{$email}}" data-role="{{$role}}"
                                                            data-province="{{$province}}" data-district="{{$district}}"
                                                            data-sector="{{$sector}}" data-id="{{$id}}"
                                                            data-toggle="modal" data-target="#edit_modal">Edit
                                                    </button>--}}{{--
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>--}}
                                </table>
                                <!--end: Datatable -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end:: Content -->
@endsection

@push('scripts')
    <script src="{{ asset('assets/vendors/general/sweetalert2/dist/sweetalert2.min.js')}}"></script>
    <script src="{{ asset('assets/vendors/custom/js/vendors/sweetalert2.init.js')}}"></script>
@endpush


@push('end_scripts')
    {{--    <script src="{{ asset('js/app.js')}}"></script>--}}
{{--    <script src="{{ asset('js/users.js')}}"></script>--}}
    <script>
        $(document).ready(function() {

            let table = $('#kt_table_1_2');
            var pathname = window.location.pathname;
console.log(pathname);
            // begin first table
            table.DataTable({
                responsive: true,
                processing: true,
                serverSide: true,
                ajax:'ajax'+ pathname,
                columns: [
                    {data: 'DT_RowIndex', searchable: false, orderable: false, className: 'text-center'},
                    {data: 'name', name: 'name'},
                    {data: 'role', name: 'role', orderable: false, searchable: false },
                    {data: 'telephone', name: 'telephone'},
                    {data: 'email', name: 'email', render: function(data,type,full,meta) { return data !==  null ? '<a class="normal-link" href="mailto:'+ data +'" target="_blank">'+ data +'</a>' : '-' }},
                    // {data: 'deployment', name: 'deployment', orderable: false, searchable: false,},
                    {data: 'action', name: 'action', orderable: false, searchable: false, className: 'text-center'}
                ],
                columnDefs: [],
                "aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]],
                "iDisplayLength": 25,
                initComplete: function() {


                    $("#kt_table_1_2_length").prepend('<div class="dropdown dropdown-inline"><button type="button" class="btn btn-label-success btn-sm btn-bold dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="flaticon-more-1"></i> </button> <div class="dropdown-menu dropdown-menu-right"> <ul class="kt-nav"> <li class="kt-nav__section kt-nav__section--first"> <span class="kt-nav__section-text">Export Tools</span> </li> <li class="kt-nav__item"> <a href="#" class="kt-nav__link" id="export_print"> <i class="kt-nav__link-icon la la-print"></i> <span class="kt-nav__link-text">Print</span> </a> </li> <li class="kt-nav__item"> <a href="#" class="kt-nav__link" id="export_copy"> <i class="kt-nav__link-icon la la-copy"></i> <span class="kt-nav__link-text">Copy</span> </a> </li> <li class="kt-nav__item"> <a href="#" class="kt-nav__link" id="export_excel"> <i class="kt-nav__link-icon la la-file-excel-o"></i> <span class="kt-nav__link-text">Excel</span> </a> </li> <li class="kt-nav__item"> <a href="#" class="kt-nav__link" id="export_csv"> <i class="kt-nav__link-icon la la-file-text-o"></i> <span class="kt-nav__link-text">CSV</span> </a> </li> <li class="kt-nav__item"> <a href="#" class="kt-nav__link" id="export_pdf"> <i class="kt-nav__link-icon la la-file-pdf-o"></i> <span class="kt-nav__link-text">PDF</span> </a> </li> </ul> </div> </div> &nbsp;&nbsp;&nbsp;') }

            });





        });

        function deactivateUser(user_id) {
            swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, deactivate!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then(function(result){
                if (result.value) {
                    document.getElementById('deactivate-' + user_id).submit();
                    swal.fire(
                        'Deactivated!',
                        'Your user has been deactivated.',
                        'success'
                    )
                    // result.dismiss can be 'cancel', 'overlay',
                    // 'close', and 'timer'
                } else if (result.dismiss === 'cancel') {
                    swal.fire(
                        'Cancelled',
                        'Your imaginary user is safe :)',
                        'error'
                    )
                }
            });
        }

        function restoreUser(user_id) {
            swal.fire({
                title: 'Are you sure?',
                text: "This user will get all former privilleges !",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, Restore!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then(function(result){
                if (result.value) {
                    document.getElementById('restore-' + user_id).submit();
                    swal.fire(
                        'Restored!',
                        'Your user has been restored.',
                        'success'
                    )
                    // result.dismiss can be 'cancel', 'overlay',
                    // 'close', and 'timer'
                } else if (result.dismiss === 'cancel') {
                    swal.fire(
                        'Cancelled',
                        'Your imaginary user is safe :)',
                        'error'
                    )
                }
            });
        }
    </script>
@endpush