routes/web.php
<?php


Route::get('/', 'HomeController@index')->name('index');
Route::get('/token', 'UsersController@generateToken');
Route::get('/country','CountryController@index')->name('country.dashboard');


Auth::routes(['verify' => true]);

Route::get('create-password', 'Auth\CreatePasswordController@index')->name('create-password-index');
Route::post('create-password', 'Auth\CreatePasswordController@store')->name('create-password');

Route::group(['middleware'=>'auth'], function() {

Route::group(['middleware'=>'administrator','prefix'=>'users'],function () {
    Route::get('/', 'UsersController@index')->name('users.index');
    Route::post('/', 'UsersController@store')->name('users.store');
    Route::post('/update', 'UsersController@update')->name('users.update');
    Route::post('/updateFew', 'UsersController@updateFew')->name('users.updateFew');
    Route::delete('/{user_id}', 'UsersController@destroy')->name('users.destroy');
    Route::post('/{user_id}', 'UsersController@restore')->name('users.restore');

});

Route::post('/missed-card-payment', 'PaymentsController@missedCardPayment')->name('missed-card-payment');
Route::prefix('cooperatives')->group(function () {
    Route::get('/', 'cooperativesController@index')->name('cooperatives.index');    
    Route::post('/', 'cooperativesController@store')->name('cooperatives.store');
    Route::post('/update', 'cooperativesController@update')->name('cooperatives.update');
    Route::post('/destroy', 'cooperativesController@destroy')->name('cooperatives.destroy'); 
});
Route::prefix('bonus')->group(function () {
Route::post('/store', 'BonusController@store')->name('bonus.store');
});
Route::post('sendSms','SmsController@sms')->name('sms');
Route::post('sms_destroy','SmsController@sms_destroy')->name('sms_destroy');
Route::resource('sms','SmsController');


Route::get('/deleted_users', 'UsersController@deleted_users')->name('users.deleted');


Route::prefix('ajax')->group(function() {
    Route::get('users', 'UsersController@getUsers');
    Route::get('deleted_users', 'UsersController@getDeletedUsers');
    Route::get('districts', 'DataController@getDistricts');
    Route::get('sectors', 'DataController@getSectors');
    Route::get('cells', 'DataController@getCells');
    Route::get('villages', 'DataController@getVillages');
});
Route::get('/edit/{id}', 'UsersController@edit')->name('users_edit');


//Route::get('/login_page', function () { return view('pages.login');})->name('login_page');
//Route::get('/country','CountryController@index')->name('country');
Route::get('/district/{id}', 'DistrictController@index')->name('district');
Route::get('/province/{id}', 'ProvinceController@index')->name('province');
Route::get('/sector/{id}', 'SectorController@index')->name('sector');
Route::get('/cooperative/{id}', 'CooperativeController@index')->name('cooperative');
Route::get('/cooperatives_list/{id}', 'CooperativeController@cooperatives')->name('cooperatives');
Route::post('/update_cooperative', 'cooperativesController@update')->name('update_cooperative');
Route::post('/register_cooperative', 'cooperativesController@store')->name('register_cooperative');
//Route::get('/home', 'HomeController@index')->name('home');
Route::post('/update_user', 'UsersController@update')->name('update_user');
Route::post('/register_user', 'UsersController@create')->name('register_user');
Route::get('/password_generate/{id}', 'UsersController@password_generate')->name('password_generate');
Route::post('/password_update', 'UsersController@password_update')->name('password_update');
//Route::post('dynamic_dependent/fetch', 'UsersController@fetch')->name('dynamicdependent.fetch');

//Route::get('/test', 'PaymentsController@test')->name('cooperatives');

Route::resource('motorcyclist', 'MotorcyclistController');
Route::post('/motorcyclist_update', 'MotorcyclistController@update')->name('motorcyclist_update');
Route::post('/motorcyclist_delete', 'MotorcyclistController@destroy')->name('motorcyclist_delete');

Route::get('/card/{type}/{id}', 'MotorcyclistController@card')->name('card');

// Route::get('/cooperative_cards/{id}', 'MotorcyclistController@cooperative_cards')->name('cooperative_cards');
Route::post('/card_id', 'MotorcyclistController@card_id')->name('card_id');
Route::get('/reloadFailed', 'BprResponseController@reloadFailed')->name('reloadFailed');
});
Route::view('/search', 'pages.search')->name('search');
Route::any("/motari", "API\MotocyclistController@info")->name('info');

// Route::prefix('v1')->group(function () {    
//     Route::post('validate', 'API\MotocyclistController@motari_equity');
// });

resources/views/pages/card.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Print Card</title>
    <style> 
    @media print {

    @page {size: legal landscape;margin: 0;}
    #print {page-break-before: always;height: 100%; width: 100%;} 
    #content {page-break-before: always;height: 100%; width: 100%;font-size: 40px;} 

   
 
}
table td.shrink {
    white-space:nowrap
}
table td.expand {
    width: 99%
}


    </style>
</head>
<body onload="window.print()" onafterprint="javascript:history.go(-1)">
  @foreach($datas as $data)

    <div id="print" style="background-image:url({{url('background/bg.jpeg')}});
/*      position:fixed;
*/      margin-top:0px;
        background-size: cover;
        margin-left:0px;
        width: 1344px;
        height: 810px;">  
 
  
<div id="content" style="
      width: 80%;
      height: 50%;
      top: 35%;
      margin: 0 auto;
      position: relative;
      font-family: Arial, Helvetica, sans-serif;font-weight: bold;">

<table border="0" width="100%" height="100%">
    <tr>
        <td width="23%" >
          <br><br>
          {{--<img src="{{$data->photoExists()}}" style="max-width: 100%;--}}
          {{-- <div style="
          background-image:url({{$data->photoExists()}}); 
          background-repeat: no-repeat; 
          max-width: 100%;
          background-size: cover;
          background-position: center;
          max-height: 100%; 
          width: 280px;
          border-radius: 25px;
          height: 280px;"> --}}
          <div><img src="{{$data->photoExists()}}" style=
          "max-width: 100%;
           max-height: 100%;
           border-radius: 25px;
           width: 280px;
           height: 280px; ">
         </div>

        </td>
        
        <td width="2%"></td>
        <td width="75%">
          
            <table border="0" width="100%" height="100%">
                <tr>
                    <td></td><td>{{strtoupper($data->cooperative->district)}}</td>
                </tr>
                <tr>
                    <td width="30%">Names  </td><td>:   {{$data->name}}</td>
                </tr>
                <tr>
                <td width="30%">Cooperative  </td><td>:   {{$data->cooperative->acronym}}</td>
               </tr>
               <tr>
                    <td width="30%">Kode  </td><td>:   {{$data->code}}</td>
               </tr> 
               <tr>
                    <td width="30%">Izarangira  </td><td>:   {{ $data->created_at->addYear(2)->format('m/Y') }}</td>
               </tr> 
               <tr></tr>              
               <tr></tr>              
                           
            </table>
        </td>
    </tr>
</table>
</div>
            </div>

            @endforeach
</body>

</html>

           
        
                
 

                    

resources/views/pages/cooperative.blade.php
@extends('layouts.master')
@section('title', $cooperative)

@section('content')
@include('include.subheader')
@include('include.filter')
<!-- begin:: Content -->
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <!--Begin::Dashboard 3-->
    <div class="row">
        <div class="col-md-7">       
         <!--Begin::Section-->
          @include('include.dataintables')

        </div>
        <div class="col-md-5">
                <div class="kt-portlet">
                    <div class="kt-portlet__head">
                        <div class="kt-portlet__head-label">
                            <h3 class="kt-portlet__head-title">
                                Amakoperative
                            </h3>
                        </div>
                    </div>
                    <div class="kt-portlet__body">
                        <!--begin::Timeline 1-->
                        <div class="kt-list-timeline">
                            <div class="kt-list-timeline__items">
                                @foreach($cooperatives as $cooperative)
                                    <div class="kt-list-timeline__item">
                                        <span class="kt-list-timeline__badge {{ randomTimeLineBadge() }}"></span>
                                        <span class="kt-list-timeline__text"><a
                                                href="/cooperatives_list/{{$group_cooperative=$cooperative->id}}">{{$cooperative->name}}</a><span class="pull-right">{{count_members('cooperative_id',$group_cooperative)}}</span></span>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <!--end::Timeline 1-->
                        <div class="kt-separator kt-separator--space-lg kt-separator--border-dashed"></div>
                    </div>
                </div>
            </div>
    </div>
</div>
<!-- end:: Content -->
</div>
</div>
</div>

@endsection
@push('end_scripts')
{{-- @include('include.date_graph_datatable')
 --}}

@include('include.edit_member_modal_js') 




{{-- <script>
    $('#members').hide();
    
    $('#member').click(function() {
    $('#transactions').hide();
    $('#members').show();
    
});
    $('#transaction').click(function() {
    $('#members').hide();
    $('#transactions').show();
    
});
</script> --}}

@endpush

resources/views/pages/cooperative_cards.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Print Card</title>
    <style> 
@media print {

    @page {size: legal landscape;margin: 0;}
    #print {page-break-before: always;height: 100%; width: 100%;} 
    #content {page-break-before: always;height: 100%; width: 100%;font-size: 30px;} 

    
}
table td.shrink {
    white-space:nowrap
}
table td.expand {
    width: 99%
}

    </style>
</head>
<body onload="window.print()" onafterprint="javascript:history.go(-1)">
  @foreach($datas as $data)
    <div id="print" style="background-image:url({{url('photo/background/bg.png')}});
/*      position:fixed;
*/      margin-top:0px;
        background-size: cover;
        margin-left:0px;
        width: 1344px;
        height: 810px;">  
 
  
<div id="content" style="
      width: 80%;
      height: 50%;
      top: 35%;
      margin: 0 auto;
      position: relative;
      font-family: Arial, Helvetica, sans-serif;font-weight: bold;">

<table border="0" width="100%" height="100%">
    <tr>
        <td width="20%"><img src="/photo/{{$data->photo}}" style="max-width: 100%;
    max-height: 100%;"></td>
    <td width="1%"></td>
        <td width="79%">
            <table border="0" width="100%" height="100%">
                <tr>
                    <td colspan="2"><center>{{$data->cooperative->district}}</center></td>
                </tr>
                <tr>
                    <td width="20%">Names</td><td>: {{$data->name}}</td>
                </tr>
                <tr>
                <td width="20%">Cooperative</td><td>: {{$data->cooperative->acronym}}</td>
               </tr>
               <tr>
                    <td width="20%">Kode</td><td>: {{$data->code}}</td>
               </tr> 
               <tr>
                    <td width="20%">Izarangira</td><td>: {{'06/2022'}}</td>
               </tr>
               <tr>
               </tr>
               <tr>                    
               </tr>            
            </table>
        </td>
    </tr>
</table>
</div>
            </div>
            @endforeach
</body>
</html>

           
        
                
 

                    

resources/views/pages/cooperatives.blade.php
    @extends('layouts.master')
    @section('title', 'Cooperatives')
    {{-- @push('styles')
    <style type="text/css">
        .select2-container--default .select2-selection--single .select2-selection__rendered {
            background: #e1e3ec;
        }
        .select2-container {
            margin-right: 10px;
        }
        .btn.btn-clean i {
            color: #2dc7bf;
        }
    </style>
    @endpush --}}
    @section('content')
    <!-- begin:: Subheader -->
    <div class="kt-subheader   kt-grid__item" id="kt_subheader">
    </div>
    <!-- end:: Subheader -->
    <!-- begin:: Content -->
    <div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
        <!--Begin::Dashboard 3-->
        <div class="row">
            <div class="col-md-12">
                <!--Begin::Section-->
                <div class="row">
                    <div class="col-md-7">
                        <div class="kt-portlet kt-portlet--height-fluid kt-portlet--mobile ">
                            <div
                            class="kt-portlet__head kt-portlet__head--lg kt-portlet__head--noborder kt-portlet__head--break-sm">
                            <div class="kt-portlet__head-label">
                                <button type="button" class="btn btn-primary" data-toggle="modal"
                                data-target="#add_cooperative_modal">
                                <i class="flaticon2-plus-1"></i>
                                Ongeramo koperative
                                </button>
                           
            
</div>

</div>
<div class="kt-portlet__body">
    
    <table class="table table-striped- table-bordered table-hover table-checkable"
    id="data-table-cooperative">
    <thead>
        <tr>
            <th>#</th>
            <th>Izina</th>
            <th>Impine</th>
            <th>Akarere</th>            
{{--             <th>BPR Account</th>            
 --}}            <th width="100px">Ibikorwa</th>                         
        </tr>
    </thead>
    
</table>
<!--end: Datatable -->
</div>
</div>
</div>

<div class="col-md-5">
                <div class="kt-portlet" style="height:805px;overflow:scroll;">
                    <div class="kt-portlet__head">
                        <div class="kt-portlet__head-label">
                            <right><h3 class="kt-portlet__head-title">
                                                            <span class="kt-list-timeline__text">Amakarita yo gusohora&nbsp;&nbsp;<span>{{allCard_number()}}</span></span>
                                                        </h3></right>
                        </div>
                    </div>
                    <div class="kt-portlet__body">
                        <!--begin::Timeline 1-->
                        <div class="kt-list-timeline">
                            <div class="kt-list-timeline__items">
                                @foreach($amakarita as $cooperative)
                                    <div class="kt-list-timeline__item">
                                        <span class="kt-list-timeline__badge {{ randomTimeLineBadge() }}"></span>
                                        <span class="kt-list-timeline__text">@if(Auth::user()->role==1)
                                                <a href="{{route('card',['cooperative_id',$cooperative->id])}}">@endif{{$cooperative->name}}</a>
                                                <span class="pull-right">{{card_number($cooperative->id)}}</span></span>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <!--end::Timeline 1-->
                        <div class="kt-separator kt-separator--space-lg kt-separator--border-dashed"></div>
                    </div>
                </div>
            </div>

</div>
</div>
</div>
</div>
@include('include.edit_cooperative_modal')
@include('include.add_cooperative_modal')
@include('include.delete_cooperative_modal') 
@include('include.add_member_modal')
@include('include.location') 

@endsection

@push('end_scripts')
@include('include.sms_modal_js') 
<script type="text/javascript">
  $(function () {
    
    var table = $('#data-table-cooperative').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{route('cooperatives.index')}}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'name', name: 'name'},
            {data: 'acronym', name: 'acronym'},
            {data: 'district', name: 'district'},
            // {data: 'bpr_account', name: 'bpr_account'},
            {data: 'actions', name: 'actions', orderable: false, searchable: false},
        ]
    });
    
  });
</script>

{{-- <script src="{{ asset('js/app.js')}}"></script>
<script src="{{ asset('js/cooperatives.js')}}"></script> --}}
@endpush

resources/views/pages/country.blade.php
@extends('layouts.master')

@section('title', 'Country Level')

@section('content')

    @include('include.subheader')
    @push('styles')
<style>
/* Style the tab */
.tab {
overflow: hidden;
/*border: 1px solid #00f;*/
/*background-color: #f1f1f1;*/
}
/* Style the buttons inside the tab */
.tab button {
background-color: inherit;
float: left;
border: none;
outline: none;
cursor: pointer;
padding: 7px 8px;
transition: 0.3s;
font-size: 18px;
}
/* Change background color of buttons on hover */
.tab button:hover {
background-color: #ddd;
}
/* Create an active/current tablink class */
.tab button.active {
background-color: #ccf;
}
/* Style the tab content */
.tabcontent {
display: none;
/*padding: 6px 12px;
border: 1px solid #ccc;
border-top: none; */
}
</style>
@endpush

    <!-- begin:: Content -->
    <div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
        <!--Begin::Dashboard 3-->
        <div class="row">
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12">
                        <div>
                            <div class="col-md-15">
                                <div class="kt-portlet kt-portlet--height-fluid-half kt-portlet--border-bottom-brand">
                                    <div class="kt-portlet__body kt-portlet__body--fluid">
                                        <div class="kt-widget26">
                                            <div class="kt-widget26__content">
                                                <a href="#" style="color: #a7abc3">
                                                    
                                                    <span class="kt-widget26__desc"><a href="#">{{$group="Kigali City"}}</a></span>
                                                      <span class="kt-widget26__number" style="color: #646c9a">{{count_members('province',$group)}}</span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-15">
                                <div class="kt-portlet kt-portlet--height-fluid-half kt-portlet--border-bottom-success">
                                    <div class="kt-portlet__body kt-portlet__body--fluid">
                                        <div class="kt-widget26">
                                            <div class="kt-widget26__content">
                                                <a href="#" style="color: #a7abc3">
                                                   
                                                    <span class="kt-widget26__desc"><a
                                                            href="#">{{$group="Northern Province"}}</a></span>
                                                            <span class="kt-widget26__number" style="color: #646c9a">{{count_members('province',$group)}}</span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-15">
                                <div class="kt-portlet kt-portlet--height-fluid-half kt-portlet--border-bottom-warning">
                                    <div class="kt-portlet__body kt-portlet__body--fluid">
                                        <div class="kt-widget26">
                                            <div class="kt-widget26__content">
                                                <a href="#" style="color: #a7abc3">
                                                    
                                                    <span class="kt-widget26__desc"><a
                                                            href="#">{{$group="Southern Province"}}</a></span>
                                                            <span class="kt-widget26__number" style="color: #646c9a">{{count_members('province',$group)}}</span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-15">
                                <div class="kt-portlet kt-portlet--height-fluid-half kt-portlet--border-bottom-danger">
                                    <div class="kt-portlet__body kt-portlet__body--fluid">
                                        <div class="kt-widget26">
                                            <div class="kt-widget26__content">
                                                <a href="#" style="color: #a7abc3">
                                                    
                                                    <span class="kt-widget26__desc"><a
                                                            href="#">{{$group='Eastern Province'}}</a></span>
                                                            <span class="kt-widget26__number" style="color: #646c9a">{{count_members('province',$group)}}</span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-15">
                                <div class="kt-portlet kt-portlet--height-fluid-half kt-portlet--border-bottom-info">
                                    <div class="kt-portlet__body kt-portlet__body--fluid">
                                        <div class="kt-widget26">
                                            <div class="kt-widget26__content">
                                                <a href="#" style="color: #a7abc3">
                                                   
                                                    <span class="kt-widget26__desc"><a
                                                            href="#">{{$group='Western Province'}}</a></span>
                                                            <span class="kt-widget26__number" style="color: #646c9a">{{count_members('province',$group)}}</span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                    
                <!--Begin::Section-->
{{--                 @include('include.dataintables')
 --}}
<!-- transactions--> 



<div class="row">
    <div class="col-md-12">
         @include('include.dataintable')
            </div>
        </div>
    </div>





<!-- end -->
            
            <div class="col-md-3">
                <div class="kt-portlet">
                    <div class="kt-portlet__head">
                        <div class="kt-portlet__head-label">
                            <h3 class="kt-portlet__head-title">
                                <center>uturere</center>
                            </h3>
                        </div>
                    </div>
                    <div class="kt-portlet__body">
                        <!--begin::Timeline 1-->
                        <div class="kt-list-timeline">
                            <div class="kt-list-timeline__items">
                                @foreach($districts as $district)
                                    <div class="kt-list-timeline__item">
                                        <span class="kt-list-timeline__badge {{ randomTimeLineBadge() }}"></span>   

                                        <span class="kt-list-timeline__text"><a href="#" data-c_id=" {{$district->district}} " data-origin="district" data-toggle="modal" data-target="#sms_modal"><i class="la la-envelope"></i></a>
                                        </span>

                                        <span class="kt-list-timeline__text align-left"><a
                                                href="/cooperative/{{$district->district}}">{{$group_district=$district->district}}</a>
                                                <span class="pull-right">{{count_members('district',$group_district)}}</span>
                                            </span>
                                                
                                            
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <!--end::Timeline 1-->
                        <div class="kt-separator kt-separator--space-lg kt-separator--border-dashed"><br>
                            @if(Auth::user()->role==1)
            <a href="{{route('reloadFailed')}}"><center>Reload failed({{countBprFailed()}})</center></a>
            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end:: Content -->
@endsection

@push('end_scripts')
    @include('include.sms_modal_js') 


{{--     @include('include.datatable_actions_members')   
 --}}   
@endpush

resources/views/pages/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/sms.blade.php
@extends('layouts.master')
@section('title', 'sms')
@section('content')
<!-- begin:: Subheader -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
</div>
<!-- end:: Subheader -->
<!-- begin:: Content -->
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <!--Begin::Dashboard 3-->
    
    <!--Begin::Section-->
    <div class="row justify-content-center">
        <div class="col-md-auto">
            <div class="kt-portlet kt-portlet--height-fluid kt-portlet--mobile justify-content-center">
                            <div
                            class="kt-portlet__head kt-portlet__head--lg kt-portlet__head--noborder kt-portlet__head--break-sm">
                            <div class="kt-portlet__head-label">
                        <center>
                        <button type="button" class="btn btn-primary text-center" data-c_id="Bose" data-origin="all" data-toggle="modal" data-target="#sms_modal">
                        <i class="la la-envelope"></i>
                        SMS to All
                        </button>  
                    </center>
                        
                    </div>

</div>
<div class="kt-portlet__body">
                    
                    <table class="table table-striped table-condensed table-hover table-checkable"
                        id="data-table-sms">
                        <thead class="bg bg-light">
                            <tr>
                                <th>#</th>
                                <th>Uwohereje</th>
                                <th>Abakira</th>
                                <th>Abakira Umubare</th>
                                <th>Ubutumwa</th>
                                <th>Umubare w'inyuguti</th>
                                <th>Igihe</th>
                                <th width="100px">Ibikorwa</th>
                            </tr>
                        </thead>
                    </table>
                    <!--end: Datatable -->
                </div>
            </div>
        </div>
    </div>
</div>

@include('include.edit_sms_modal')
@include('include.delete_sms_modal')
@endsection
{{-- 
@push('end_scripts')
@include('include.edit_cooperative_modal_js')
@include('include.sms_modal_js')
@endpush --}}
@push('end_scripts')
<script type="text/javascript">
$(function () {
var table = $('#data-table-sms').DataTable({
processing: true,
serverSide: true,
ajax: "{{ route('sms.index') }}",
columns: [
{data: 'DT_RowIndex', name: 'DT_RowIndex'},
{data: 'sender', name: 'sender'},
{data: 'cooperative_id', name: 'cooperative_id'},
{data: 'recipients', name: 'recipients'},
{data: 'message', name: 'message'},
{data: 'characters', name: 'characters'},
{data: 'updated_at', name: 'updated_at'},
{data: 'actions', name: 'actions', orderable: false, searchable: false},
]
});
});
</script>
@endpush